services:

  postgres:
    image: postgres:17
    container_name: postgres-db

    environment:
      POSTGRES_DB: securityDB
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  springboot:
    build: .
    container_name: security-app

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/securityDB
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}


volumes:
  postgres_data: