# ==========================================
# Application
# ==========================================

spring.application.name=SecurityLearning


# ==========================================
# Database
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# ==========================================
# Hibernate SQL Logging (Development)
# ==========================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ==========================================
# JWT
# ==========================================

jwt.secretKey=${JWT_SECRET_KEY}


# ==========================================
# Google OAuth2
# ==========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# ==========================================
# GitHub OAuth2
# ==========================================

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}


# ==========================================
# Logging
# ==========================================

logging.level.root=INFO

logging.level.com.example.SecurityLearning=DEBUG

logging.file.name=logs/application.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n